name: photo_manager_example
description: Demonstrates how to use the image_scanner plugin.
version: 2.1.0+7
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^0.13.0
  oktoast: ^3.1.3+1
  path_provider: ^2.0.5
  photo_manager:
    path: ../
  provider: ^6.0.0
  video_player: ^2.1.14

dev_dependencies:
  flutter_lints: any

flutter:
  uses-material-design: true
